[project]
name = "bikeshed-builder"
version = "0.0.0+4.1.6"
classifiers = ["Private :: Do Not Upload"]
dependencies = ["bikeshed==4.1.6"]

[project.optional-dependencies]
dev = ["pyinstaller", "black"]
