name: gh release create
on:
  workflow_dispatch:
    inputs:
      version:
        description: "1.2.3 or similar"
        type: string
        required: true
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  task-build:
    uses: ./.github/workflows/task-build.yml
  gh-release-create:
    needs: task-build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: |
          for f in $ARTIFACTS; do
            if [[ $f == *windows* ]]; then
              wd="$PWD"
              (cd "$f" && powershell Compress-Archive . "$wd/$f.zip")
            else
              wd="$PWD"
              (cd "$f" && tar -czvf "$wd/$f.tar.gz" .)
            fi
          done
        env:
          ARTIFACTS: >-
            bikeshed-x86_64-linux-unknown-gnu
            bikeshed-x86_64-pc-windows-msvc
            bikeshed-arm64-apple-darwin
            bikeshed-x86_64-apple-darwin
      - run: |
          gh release create \
            "v$VERSION" \
            --generate-notes \
            *.tar.gz *.zip
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
