name: gh release create
on:
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
        default: false
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  poe-build:
    uses: ./.github/workflows/poe-build.yml
  get-version:
    outputs:
      version: ${{ steps.yq.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: yq
        uses: mikefarah/yq@master
        with:
          cmd: yq .tool.poetry.version pyproject.toml
  gh-release-create:
    needs: [poe-build, get-version]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - shell: bash -ex {0}
        run: |
          for f in *; do
            if [[ $f == *windows* ]]; then
              wd="$PWD"
              (cd "$f" && zip -r "$wd/$f.zip" .)
            else
              wd="$PWD"
              (cd "$f" && tar -czf "$wd/$f.tar.gz" .)
            fi
          done
      - run: |
          gh release create \
            "v$VERSION" \
            $DRAFT_FLAG \
            --generate-notes \
            *.tar.gz *.zip
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          VERSION: ${{ needs.get-version.outputs.version }}
          DRAFT_FLAG: ${{ github.event.inputs.draft && '--draft' || '' }}
