name: gh release create
on:
  workflow_dispatch:
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  task-build:
    uses: ./.github/workflows/task-build.yml
  gh-release-create:
    needs: task-build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - shell: bash -ex {0}
        run: |
          for f in dist/*; do
            if [[ $f == *windows* ]]; then
              wd="$PWD"
              (cd "$f" && zip -r "$wd/$f.zip" .)
            else
              wd="$PWD"
              (cd "$f" && tar -czf "$wd/$f.tar.gz" .)
            fi
          done
      - id: yq
        uses: mikefarah/yq@master
        with:
          cmd: yq .project.version pyproject.toml
      - run: |
          gh release create \
            "v$VERSION" \
            --generate-notes \
            dist/*.tar.gz dist/*.zip
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          VERSION: ${{ steps.yq.outputs.result }}
