name: Test install scripts
on:
  push:
    branches: ["main"]
    paths:
      - install.sh
      - install.ps1
      - .github/workflows/test.yml
  pull_request:
    paths-ignore:
      - install.sh
      - install.ps1
      - .github/workflows/test.yml
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck install.sh
  install-sh:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: cat install.sh | sh
      - run: echo "$HOME/.bikeshed" >> "$GITHUB_PATH"
      - run: bikeshed --version
  install-ps1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: nohup python -m http.server & sleep 3
      - run: |
          irm http://localhost:8000/install.ps1 | iex
          bikeshed --version
